ToDoItems/Models/ErrorViewModel.cs
namespace ToDoItems.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoItems/Models/Item.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace ToDoItems.Models
{
	public class Item
	{
		[JsonProperty(PropertyName = "id")]
		public string? Id { get; set; }

		[Required]
		[JsonProperty(PropertyName = "name")]
		public string? Name { get; set; }

		[Required]
		[JsonProperty(PropertyName = "description")]
		public string? Description { get; set; }

		[JsonProperty(PropertyName = "completed")]
		public bool Completed { get; set; }

        [JsonProperty(PropertyName = "personId")]
        public string? PersonId { get; set; }

        public Person? Person { get; set; }
    }
}

ToDoItems/Models/Person.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using static NuGet.Client.ManagedCodeConventions;

namespace ToDoItems.Models
{
    public class Person
    {
        [JsonProperty(PropertyName = "id")]
        public string? Id { get; set; }

        [Required]
        [JsonProperty(PropertyName = "firstname")]
        public string? FirstName { get; set; }

        [Required]
        [JsonProperty(PropertyName = "lastname")]
        public string? LastName { get; set; }

        [Required]
        [JsonProperty(PropertyName = "oib")]
        public string? OIB { get; set; }
    }
}

ToDoItems/ViewModels/VMItem.cs
using Newtonsoft.Json;
using static NuGet.Client.ManagedCodeConventions;

namespace ToDoItems.ViewModels
{
    public class VMItem
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public bool Completed { get; set; }
        public string? Person { get; set; }
        public List<string>? People { get; set; }
    }
}

ToDoItems/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoItems.Dal;
using ToDoItems.Models;
using ToDoItems.ViewModels;

namespace ToDoItems.Controllers
{
    public class ItemController : Controller
    {

		private static readonly ICosmosDbService service = CosmosDbServiceProvider.Service!;
        private static readonly ICosmosDbPeopleService peopleService = CosmosDbServiceProvider.PeopleService!;

        public async Task<ActionResult> Index()
		{
            var items = await service.GetItemsAsync("SELECT * FROM Item");

            foreach (var item in items)
            {
                item.Person = await peopleService.GetPersonAsync(item.PersonId);
            }

            return View(items);
        }

		public async Task<ActionResult> Create()
		{
			var people = await peopleService.GetPeopleAsync("SELECT * FROM Person");
			var vmPeople = people.Select(x => x.FirstName).ToList();
            var vmItem = new VMItem();
            vmItem.People = vmPeople;

            return View(vmItem);
		}

		[HttpPost]
		public async Task<ActionResult> Create(VMItem vmItem)
		{
			if (ModelState.IsValid)
			{
				Item item = new Item();
				item.Name = vmItem.Name;
				item.Description = vmItem.Description;
				item.Completed = vmItem.Completed;
                var people = await peopleService.GetPeopleAsync("SELECT * FROM Person");
                var personId = people.FirstOrDefault(x => x.FirstName.Equals(vmItem.Person)).Id;
				item.PersonId = personId;
                item.Id = Guid.NewGuid().ToString();
				await service.AddItemAsync(item);
				return RedirectToAction(nameof(Index));
			}

			return View(vmItem);
		}

		public async Task<ActionResult> Edit(string id) => await ShowItem(id);

		public async Task<ActionResult> Delete(string id) => await ShowItem(id);

		public async Task<ActionResult> Details(string id) => await ShowItem(id);

		private async Task<ActionResult> ShowItem(string id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			var item = await service.GetItemAsync(id);
			if (item == null)
			{
				return NotFound();
			}
			return View(item);
		}

		// copy from Create
		[HttpPost]
		public async Task<ActionResult> Edit(Item item)
		{
			if (ModelState.IsValid)
			{
				await service.UpdateItemAsync(item);
				return RedirectToAction(nameof(Index));
			}
			return View(item);
		}

		// copy from Edit post
		[HttpPost]
		public async Task<ActionResult> Delete(Item item)
		{
			await service.DeleteItemAsync(item);
			return RedirectToAction(nameof(Index));

		}

	}
}

ToDoItems/Controllers/PersonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ToDoItems.Dal;
using ToDoItems.Models;

namespace ToDoItems.Controllers
{
    public class PersonController : Controller
    {
        private static readonly ICosmosDbPeopleService peopleService 
            = CosmosDbServiceProvider.PeopleService!;
        // GET: PersonController
        public async Task<ActionResult> Index()
        {
            return View(await peopleService.GetPeopleAsync("SELECT * FROM Person"));
        }

        // GET: PersonController/Details/5
        public async Task<ActionResult> Details(string id) => await ShowPerson(id);

        private async Task<ActionResult> ShowPerson(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var person = await peopleService.GetPersonAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // GET: PersonController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonController/Create
        [HttpPost]
        public async Task<ActionResult> Create(Person person)
        {
            if (ModelState.IsValid)
            {
                person.Id = Guid.NewGuid().ToString();
                await peopleService.AddPersonAsync(person);
                return RedirectToAction(nameof(Index));
            }

            return View(person);
        }

        // GET: PersonController/Edit/5
        public async Task<ActionResult> Edit(string id) => await ShowPerson(id);

        // POST: PersonController/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Person person)
        {
            if (ModelState.IsValid)
            {
                await peopleService.UpdatePersonAsync(person);
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: PersonController/Delete/5
        public async Task<ActionResult> Delete(string id) => await ShowPerson(id);

        // POST: PersonController/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Person person)
        {
            await peopleService.DeletePersonAsync(person);
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoItems/Views/Item/Create.cshtml
@model ToDoItems.ViewModels.VMItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>VMItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="People" />
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="Person" asp-items="@(new SelectList(Model.People))" class="form-select mb-2"></select>
                <span asp-validation-for="Person" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoItems/Views/Item/Delete.cshtml
@model ToDoItems.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ToDoItems/Views/Item/Details.cshtml
@model ToDoItems.Models.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

ToDoItems/Views/Item/Edit.cshtml
@model ToDoItems.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoItems/Views/Item/Index.cshtml
@model IEnumerable<ToDoItems.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-controller="Person" asp-action="Index">View People</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Completed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Person)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Completed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Person.FirstName)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ToDoItems/Views/Person/Create.cshtml
@model ToDoItems.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoItems/Views/Person/Delete.cshtml
@model ToDoItems.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OIB)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ToDoItems/Views/Person/Details.cshtml
@model ToDoItems.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OIB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OIB)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

ToDoItems/Views/Person/Edit.cshtml
@model ToDoItems.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" readonly class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OIB" class="control-label"></label>
                <input asp-for="OIB" class="form-control" />
                <span asp-validation-for="OIB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoItems/Views/Person/Index.cshtml
@model IEnumerable<ToDoItems.Models.Person>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-controller="Item" asp-action="Index">ToDo List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OIB)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OIB)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ToDoItems/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoItems</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoItems.styles.css" asp-append-version="true" />
</head>
<body>
    <!--    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoItems</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoItems <!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -->
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>